<a href="https://colab.research.google.com/github/mharshavardhan224/DataAnalyst/blob/main/FUNCTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from opendatasets) (8.1.8)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2025.1.31)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.3.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.11/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [ ]:
import pandas as pd
data= pd.read_csv('/content/customer_shopping_data.csv')

In [ ]:
data.head(5)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,05-08-2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12-12-2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,09-11-2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16-05-2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24-10-2021,Kanyon

In [ ]:
data.tail()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21-09-2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22-09-2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28-03-2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16-03-2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15-10-2022,Mall of Istanbul

In [ ]:
data.shape

(99457, 10)

In [ ]:
data.dtypes

invoice_no         object
customer_id        object
gender             object
age                 int64
category           object
quantity            int64
price             float64
payment_method     object
invoice_date       object
shopping_mall      object
dtype: object

In [ ]:
data.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='object')

In [ ]:
data.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [ ]:
data.describe()

                age      quantity         price
count  99457.000000  99457.000000  99457.000000
mean      43.427089      3.003429    689.256321
std       14.990054      1.413025    941.184567
min       18.000000      1.000000      5.230000
25%       30.000000      2.000000     45.450000
50%       43.000000      3.000000    203.300000
75%       56.000000      4.000000   1200.320000
max       69.000000      5.000000   5250.000000

In [ ]:
data.dropna

<bound method DataFrame.dropna of       invoice_no customer_id  gender  age         category  quantity    price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40
1        I317333     C111565    Male   21            Shoes         3  1800.51
2        I127801     C266599    Male   20         Clothing         1   300.08
3        I173702     C988172  Female   66            Shoes         5  3000.85
4        I337046     C189076  Female   53            Books         4    60.60
...          ...         ...     ...  ...              ...       ...      ...
99452    I219422     C441542  Female   45         Souvenir         5    58.65
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46
99455    I702964     C800631    Male   56       Technology         4  4200.00
99456    I232867     C273973  Female   36         Souvenir         3    35.19

      payment_method invoice_date     shopping_mall
0        Credit Card   05-08-2022            Kanyon
1         Debit Card   12-12-2021    Forum Istanbul
2               Cash   09-11-2021         Metrocity
3        Credit Card   16-05-2021      Metropol AVM
4               Cash   24-10-2021            Kanyon
...              ...          ...               ...
99452    Credit Card   21-09-2022            Kanyon
99453           Cash   22-09-2021    Forum Istanbul
99454     Debit Card   28-03-2021         Metrocity
99455           Cash   16-03-2021      Istinye Park
99456    Credit Card   15-10-2022  Mall of Istanbul

[99457 rows x 10 columns]>

In [ ]:
data.fillna(4)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,05-08-2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12-12-2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,09-11-2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16-05-2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24-10-2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21-09-2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22-09-2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28-03-2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16-03-2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15-10-2022,Mall of Istanbul

In [ ]:
data.replace('old','new')

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,05-08-2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12-12-2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,09-11-2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16-05-2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24-10-2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21-09-2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22-09-2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28-03-2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16-03-2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15-10-2022,Mall of Istanbul

In [ ]:
data.drop_duplicates

<bound method DataFrame.drop_duplicates of       invoice_no customer_id  gender  age         category  quantity    price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40
1        I317333     C111565    Male   21            Shoes         3  1800.51
2        I127801     C266599    Male   20         Clothing         1   300.08
3        I173702     C988172  Female   66            Shoes         5  3000.85
4        I337046     C189076  Female   53            Books         4    60.60
...          ...         ...     ...  ...              ...       ...      ...
99452    I219422     C441542  Female   45         Souvenir         5    58.65
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46
99455    I702964     C800631    Male   56       Technology         4  4200.00
99456    I232867     C273973  Female   36         Souvenir         3    35.19

      payment_method invoice_date     shopping_mall
0        Credit Card   05-08-2022            Kanyon
1         Debit Card   12-12-2021    Forum Istanbul
2               Cash   09-11-2021         Metrocity
3        Credit Card   16-05-2021      Metropol AVM
4               Cash   24-10-2021            Kanyon
...              ...          ...               ...
99452    Credit Card   21-09-2022            Kanyon
99453           Cash   22-09-2021    Forum Istanbul
99454     Debit Card   28-03-2021         Metrocity
99455           Cash   16-03-2021      Istinye Park
99456    Credit Card   15-10-2022  Mall of Istanbul

[99457 rows x 10 columns]>

In [ ]:
data['invoice_no']

0        I138884
1        I317333
2        I127801
3        I173702
4        I337046
          ...
99452    I219422
99453    I325143
99454    I824010
99455    I702964
99456    I232867
Name: invoice_no, Length: 99457, dtype: object

In [ ]:
data

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,05-08-2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12-12-2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,09-11-2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16-05-2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24-10-2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21-09-2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22-09-2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28-03-2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16-03-2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15-10-2022,Mall of Istanbul

In [ ]:
data['customer_id']

0        C241288
1        C111565
2        C266599
3        C988172
4        C189076
          ...
99452    C441542
99453    C569580
99454    C103292
99455    C800631
99456    C273973
Name: customer_id, Length: 99457, dtype: object

In [ ]:
data[['customer_id','age']]

      customer_id  age
0         C241288   28
1         C111565   21
2         C266599   20
3         C988172   66
4         C189076   53
...           ...  ...
99452     C441542   45
99453     C569580   27
99454     C103292   63
99455     C800631   56
99456     C273973   36

[99457 rows x 2 columns]

In [ ]:
import pandas as pd

# Make sure this cell is executed first
data = pd.read_csv('/content/customer_shopping_data.csv')

# Now you can use data in other cells
data.loc[1]

invoice_no               I317333
customer_id              C111565
gender                      Male
age                           21
category                   Shoes
quantity                       3
price                    1800.51
payment_method        Debit Card
invoice_date          12-12-2021
shopping_mall     Forum Istanbul
Name: 1, dtype: object

In [ ]:
data.loc[2]

invoice_no           I127801
customer_id          C266599
gender                  Male
age                       20
category            Clothing
quantity                   1
price                 300.08
payment_method          Cash
invoice_date      09-11-2021
shopping_mall      Metrocity
Name: 2, dtype: object

In [ ]:
data.iloc[0,1]

'C241288'

In [ ]:
data[data['age'] > 50]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16-05-2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24-10-2021,Kanyon
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,04-11-2021,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22-08-2021,Kanyon
12,I640508,C225330,Female,67,Toys,4,143.36,Debit Card,31-07-2022,Metrocity
...,...,...,...,...,...,...,...,...,...,...
99440,I887161,C137631,Female,58,Clothing,1,300.08,Cash,22-06-2021,Kanyon
99448,I332105,C231387,Female,65,Shoes,4,2400.68,Credit Card,29-08-2021,Metropol AVM
99449,I134399,C953724,Male,65,Clothing,1,300.08,Cash,01-01-2023,Kanyon
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28-03-2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16-03-2021,Istinye Park

In [7]:
data['invoice_no'] = pd.to_numeric(data['invoice_no'], errors='coerce')
data.query('invoice_no > 50')

Empty DataFrame
Columns: [invoice_no, customer_id, gender, age, category, quantity, price, payment_method, invoice_date, shopping_mall]
Index: []

In [8]:
data.sort_values('age',ascending=False)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
46718,NaN,C132538,Male,69,Cosmetics,4,162.64,Credit Card,04-01-2021,Kanyon
46359,NaN,C168946,Female,69,Cosmetics,1,40.66,Credit Card,23-09-2022,Kanyon
87550,NaN,C148278,Female,69,Shoes,5,3000.85,Cash,16-08-2021,Kanyon
21405,NaN,C145483,Female,69,Clothing,5,1500.40,Cash,13-11-2021,Viaport Outlet
21396,NaN,C152488,Female,69,Food & Beverage,3,15.69,Cash,18-12-2022,Metropol AVM
...,...,...,...,...,...,...,...,...,...,...
60653,NaN,C897525,Female,18,Books,4,60.60,Debit Card,05-01-2021,Kanyon
19962,NaN,C283759,Male,18,Clothing,2,600.16,Credit Card,13-03-2022,Kanyon
32010,NaN,C338224,Male,18,Shoes,3,1800.51,Debit Card,08-05-2021,Zorlu Center
88359,NaN,C569728,Male,18,Toys,3,107.52,Credit Card,19-07-2021,Cevahir AVM
14653,NaN,C214001,Female,18,Clothing,1,300.08,Cash,16-06-2021,Mall of Istanbul

In [11]:
data.groupby('category_age').mean()

KeyError: 'category_age'